baseURL = "https://rimworldmultiplayer.com/"
languageCode = "en-us"
title = "Rimworld Multiplayer"
ignoreFiles = ["\\.ts$", "tsconfig.json$"]
disableKinds = ["taxonomy", "taxonomyTerm"]

# PYGMENTS (Syntax Highlighting) settings!
# I couldn't get Chroma to parse C# at all.
PygmentsUseClassic = true
PygmentsCodeFences = true
PygmentsUseClasses = true

[markup.goldmark.renderer]
unsafe= true
